### ISSUE TITLE
lvm cookbook failed to run on chef 12 client

### ISSUE THREAD

**Issue by sinfomicien** [opscode-cookbooks/lvm#42]
On my configuration, there was a big problem with chef 12 client. I started to debug what was wrong... And finally was not able to finish it.

So i started to refactor your code.. To the way that chef explain how we must do our LWRP. Then, tested the code against chef 12 client on my production servers, and everything was back.

So i just push this PR, which only refactor LWRP (change only rubocop offenses in the core code).

Hope this help ( Refactor lwrp #41 )

**Comment by evan2645** [comment]
Provided an alternate approach in https://github.com/opscode-cookbooks/lvm/issues/46 if you'd like to have a look.

**Comment by juliandunn** [comment]
This is fixed in #46.
