### ISSUE TITLE
NoMethodError for 'directory' on Chef 12.0.x

### ISSUE THREAD

**Issue by hulu1522** [opscode-cookbooks/lvm#44]
Chef 12.0.x has introduced some issues with resources inside of providers.  I already had PR #35 waiting to be pushed so I added the fix to it.  If anyone has this issue please use this repo:

https://github.com/hulu1522/lvm.git

**Comment by evan2645** [comment]
Provided an alternate approach in https://github.com/opscode-cookbooks/lvm/issues/46 if you'd like to have a look. It includes a fix for Chef12 HWRP's only.
